name: '☀️ Daily tasks'

on:
  schedule:
    # Run daily at 11:30 pm
    - cron: '30 23 * * *'

  workflow_dispatch:
    inputs:
      year:
        description: 'Year'
        required: false
      month:
        description: 'Month'
        required: false

jobs:
  run-daily-tasks:
    name: '👷 Run daily tasks'
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
      - name: '📦 Checkout'
        uses: actions/checkout@v7

      - name: '🍔 Set up Bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: '✅ Install dependencies'
        run: bun install

      - name: '🧘‍♂️ Fetch meditations value and set on Notion with given year and month'
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli set-current-value-of-meditations-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: '‍🧘‍♂️ Fetch meditations value and set on Notion with current year and month'
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli set-current-value-of-meditations-key-result

      - name: '👀 Fetch observations value and set on Notion with given year and month'
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli set-current-value-of-observations-key-result -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: '‍👀 Fetch observations value and set on Notion with current year and month'
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli set-current-value-of-observations-key-result

      - name: '🕊️ Aggregate monthly meditation data and write to vault for given year and month'
        if: "${{ github.event.inputs.year != '' && github.event.inputs.month != '' }}"
        run: bun run cli save-monthly-meditation-aggregates-to-vault -y ${{ github.event.inputs.year }} -m ${{ github.event.inputs.month }}

      - name: '🕊️ Aggregate monthly meditation data and write to vault for current year and month'
        if: "${{ github.event.inputs.year == '' && github.event.inputs.month == '' }}"
        run: bun run cli save-monthly-meditation-aggregates-to-vault

      - name: '🗄️ Commit vault back to repo'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: '🤖 Save data to vault'
          commit_user_name: '0x4444'
          commit_user_email: '0x4444@users.noreply.github.com'
          commit_author: '0x4444 <0x4444@users.noreply.github.com>'
          file_pattern: 'vault/*'

  deploy:
    name: '☁️'
    needs: [run-daily-tasks]
    uses: shivekkhurana/state-of-being/.github/workflows/cd.yml@master
    secrets: inherit
